
// Liste des ID pour createdBy
const userIds = [
  ObjectId('672b4d9d40baa2c462c73bf8'),
  ObjectId('672b4d9d40baa2c462c73bfc'),
  ObjectId('6745d269ea6dfc57b75cdb8f'),
  ObjectId('674e0b2f76ee65f151c73bf8'),
  ObjectId('674e0b2f76ee65f151c73bf9'),
  ObjectId('674eddf862cef05fd77f8ba3'),
  ObjectId('674ede87d71b94696ac73bf8'),
  ObjectId('674ede87d71b94696ac73bf9'),
  ObjectId('674ede87d71b94696ac73bfe'),
  ObjectId('675c26bb716f28c263d428b4')
];

// Fonction pour générer une date aléatoire dans les 30 prochains jours
function getRandomDate() {
  const start = new Date();
  const end = new Date();
  end.setDate(start.getDate() + 30);
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

// Liste des offres à insérer
const offers = [
  {
    title: "Analyste Financier",
    enterprise: "Banque Agricole du Burkina Faso",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.banqueagricole.bf",
    description: "Nous recherchons un analyste financier pour rejoindre notre équipe et contribuer à l'analyse des marchés financiers.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1500000,
    type: "Job",
    requirements: "Master en Finance, 3 ans d'expérience minimum",
    responsibilities: "Analyse des données financières, préparation de rapports",
    educationLevel: "Master",
    experienceLevel: "Intermédiaire",
    contractType: "CDI",
    benefits: "Assurance santé, primes annuelles",
    contactEmail: "recrutement@banqueagricole.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: true,
    applicationLink: "https://www.banqueagricole.bf/careers",
    additionalInfo: "Poste à pourvoir immédiatement",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Comptable Senior",
    enterprise: "Fiduciaire Burkina",
    enterpriseLocation: "Bobo-Dioulasso, Burkina Faso",
    enterWebsite: "https://www.fiduciairebf.bf",
    description: "Nous recherchons un comptable senior pour gérer les comptes de nos clients.",
    domain: "Finance",
    location: "Bobo-Dioulasso, Burkina Faso",
    salary: 1200000,
    type: "Job",
    requirements: "Licence en Comptabilité, 5 ans d'expérience",
    responsibilities: "Gestion des comptes clients, préparation des états financiers",
    educationLevel: "Licence",
    experienceLevel: "Senior",
    contractType: "CDD",
    benefits: "Assurance santé, formation continue",
    contactEmail: "recrutement@fiduciairebf.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Both",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: false,
    canAddOthersDoc: false,
    applicationLink: "https://www.fiduciairebf.bf/careers",
    additionalInfo: "Poste à pourvoir dans un mois",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Stagiaire en Audit Financier",
    enterprise: "KPMG Burkina Faso",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.kpmg.bf",
    description: "Nous offrons un stage en audit financier pour les étudiants en fin de cycle.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    duration: 6,
    type: "Internship",
    requirements: "Étudiant en Master Finance ou Comptabilité",
    responsibilities: "Assistance dans les missions d'audit",
    educationLevel: "Master",
    experienceLevel: "Débutant",
    contractType: "CDD",
    benefits: "Indemnité de stage, expérience professionnelle",
    contactEmail: "stage@kpmg.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: false,
    applicationLink: "https://www.kpmg.bf/careers",
    additionalInfo: "Stage rémunéré",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Gestionnaire de Portefeuille",
    enterprise: "Bourse Régionale des Valeurs Mobilières",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.brvm.org",
    description: "Nous recherchons un gestionnaire de portefeuille pour gérer les investissements de nos clients.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 2000000,
    type: "Job",
    requirements: "Master en Finance, certification CFA un plus",
    responsibilities: "Gestion des portefeuilles clients, analyse des marchés",
    educationLevel: "Master",
    experienceLevel: "Intermédiaire",
    contractType: "CDI",
    benefits: "Assurance santé, bonus annuel",
    contactEmail: "recrutement@brvm.org",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: true,
    applicationLink: "https://www.brvm.org/careers",
    additionalInfo: "Poste à pourvoir immédiatement",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Conseiller en Investissement",
    enterprise: "Banque Internationale du Burkina",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.bib.bf",
    description: "Nous recherchons un conseiller en investissement pour accompagner nos clients dans leurs projets.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1800000,
    type: "Job",
    requirements: "Licence en Finance, 2 ans d'expérience",
    responsibilities: "Conseil en investissement, gestion de portefeuille",
    educationLevel: "Licence",
    experienceLevel: "Junior",
    contractType: "CDI",
    benefits: "Assurance santé, formation continue",
    contactEmail: "recrutement@bib.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: false,
    canAddOthersDoc: false,
    applicationLink: "https://www.bib.bf/careers",
    additionalInfo: "Poste à pourvoir dans deux semaines",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Auditeur Interne",
    enterprise: "Société Générale Burkina Faso",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.societegenerale.bf",
    description: "Nous recherchons un auditeur interne pour renforcer notre équipe d'audit.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1700000,
    type: "Job",
    requirements: "Master en Audit ou Finance, 4 ans d'expérience",
    responsibilities: "Conduite des audits internes, préparation des rapports",
    educationLevel: "Master",
    experienceLevel: "Intermédiaire",
    contractType: "CDI",
    benefits: "Assurance santé, primes annuelles",
    contactEmail: "recrutement@societegenerale.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: true,
    applicationLink: "https://www.societegenerale.bf/careers",
    additionalInfo: "Poste à pourvoir immédiatement",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Analyste Crédit",
    enterprise: "Ecobank Burkina Faso",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.ecobank.bf",
    description: "Nous recherchons un analyste crédit pour évaluer les risques de crédit.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1600000,
    type: "Job",
    requirements: "Licence en Finance, 3 ans d'expérience",
    responsibilities: "Analyse des dossiers de crédit, évaluation des risques",
    educationLevel: "Licence",
    experienceLevel: "Intermédiaire",
    contractType: "CDI",
    benefits: "Assurance santé, primes annuelles",
    contactEmail: "recrutement@ecobank.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: false,
    canAddOthersDoc: false,
    applicationLink: "https://www.ecobank.bf/careers",
    additionalInfo: "Poste à pourvoir dans un mois",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Trésorier",
    enterprise: "Banque Atlantique Burkina",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.banqueatlantique.bf",
    description: "Nous recherchons un trésorier pour gérer les liquidités de l'entreprise.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1900000,
    type: "Job",
    requirements: "Master en Finance, 5 ans d'expérience",
    responsibilities: "Gestion des liquidités, prévision des flux de trésorerie",
    educationLevel: "Master",
    experienceLevel: "Senior",
    contractType: "CDI",
    benefits: "Assurance santé, bonus annuel",
    contactEmail: "recrutement@banqueatlantique.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: true,
    applicationLink: "https://www.banqueatlantique.bf/careers",
    additionalInfo: "Poste à pourvoir immédiatement",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Contrôleur de Gestion",
    enterprise: "Banque de l'Habitat du Burkina",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.bhb.bf",
    description: "Nous recherchons un contrôleur de gestion pour superviser les performances financières.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1750000,
    type: "Job",
    requirements: "Master en Contrôle de Gestion, 4 ans d'expérience",
    responsibilities: "Analyse des performances financières, reporting",
    educationLevel: "Master",
    experienceLevel: "Intermédiaire",
    contractType: "CDI",
    benefits: "Assurance santé, primes annuelles",
    contactEmail: "recrutement@bhb.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: true,
    canAddOthersDoc: true,
    applicationLink: "https://www.bhb.bf/careers",
    additionalInfo: "Poste à pourvoir dans deux semaines",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  },
  {
    title: "Chargé de Clientèle Banque",
    enterprise: "Coris Bank Burkina",
    enterpriseLocation: "Ouagadougou, Burkina Faso",
    enterWebsite: "https://www.corisbank.bf",
    description: "Nous recherchons un chargé de clientèle pour accompagner nos clients dans leurs projets.",
    domain: "Finance",
    location: "Ouagadougou, Burkina Faso",
    salary: 1300000,
    type: "Job",
    requirements: "Licence en Marketing ou Finance, 2 ans d'expérience",
    responsibilities: "Gestion des comptes clients, proposition de solutions financières",
    educationLevel: "Licence",
    experienceLevel: "Junior",
    contractType: "CDI",
    benefits: "Assurance santé, formation continue",
    contactEmail: "recrutement@corisbank.bf",
    status: "Open",
    isRemote: false,
    applicationMode: "Online",
    onlineSubmission: true,
    isRequiredCvDoc: true,
    isRequiredMlDoc: false,
    canAddOthersDoc: false,
    applicationLink: "https://www.corisbank.bf/careers",
    additionalInfo: "Poste à pourvoir dans un mois",
    createdBy: userIds[Math.floor(Math.random() * userIds.length)],
    postedDate: new Date(),
    expirationDate: getRandomDate()
  }
];

// Insertion des offres dans la collection
db.offers.insertMany(offers);